module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    theme: {
        extend: {
            spacing: {
                half: '50%',
                inherit: 'inherit',
                hero: '47rem',
                tool: '46rem',
                modalHeight: 'calc(100vh - 75px)',
                'hero-max': 'calc(100vh - 150px)',
                'city-w': 76,
                'city-h': 84,
                'city-mobile-w': 76 * 2,
                'city-mobile-h': 84 * 2,
                'venue-w': 350,
                'venue-h': 380,
                'venue-tablet-w': 350 * 0.5,
                'venue-tablet-h': 380 * 0.5,
                'venue-mobile-w': 350 * 0.3,
                'venue-mobile-h': 380 * 0.3,
                hosthero: 'calc(100vh - 90px)',
                80: '80%',
            },
            backgroundImage: {
                hero: "url('/src/assets/images/heroBackground.png')",
                tool: "url('/src/assets/images/background_img2.png')",
                vendor: "url('/src/assets/images/background_img3.png')",
                modal: "url('/src/assets/images/modalBackground.png')",
                search: "url('/src/assets/images/searchCover.png')",
                hosthero: "url('/src/assets/images/hostGirl.png')",
                hostman: "url('/src/assets/images/hostMan.png')",
            },
            transitionProperty: {
                width: 'width',
            },
            borderRadius: {
                20: 20,
            },
            fontSize: {
                20: 20,
            },
            colors: {
                black: '#000000',
                white: '#ffffff',
                slate: 'rgb(226 232 240)',
                dark: '#4A3939',
                maroon: '#6F3939',
                light: '#807979',
                dim: 'rgb(199 199 199 / 10%)',
                helper: '#716B6B',
                modalDark: '#141414',
                dimWhite: '#FFFAFA',
                modalWhite: '#FFFBFB',
                socialBorder: '#00000033',
                socialText: '#5A5A5A',
                filterBorder: '#C1A1A1',
                filterBackground: '#EEEEEE',
                filterBackgroundHover: '#E1E1E1',
                searchPlaceholder: '#AAA7A7',
                'light-maroon': '#DF7E7E',
                'light-maroon-dark': '#CE6868',
                'maroon-300': '#6F393920',
            },
            fontFamily: {
                regular: ['regular'],
                light: ['light'],
                medium: ['medium'],
                semibold: ['semibold'],
                bold: ['bold'],
                extrabold: ['extrabold'],
                mark: ['mark'],
                'roboto-regular': ['roboto-regular'],
                'roboto-bold': ['roboto-bold'],
                'inter-medium': ['inter-medium'],
            },
            maxWidth: {
                header: '23rem',
                mobile: '14rem',
            },
            lineHeight: {
                11: '58.51px',
            },
        },
        screens: {
            lg: { max: '1920px' },
            md: { max: '1200px' },
            sm: { max: '990px' },
            xs: { max: '600px' },
        },
    },

    plugins: [require('tailwindcss'), require('autoprefixer')],
}
